services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    restart: unless-stopped
    env_file:
        - .env
    environment:
      DATABASE_URL: mysql://${MYSQL_USERNAME}:${MYSQL_PASSWORD}@168.138.131.182:${MYSQL_PORT}/${MYSQL_DATABASE}?createDatabaseIfNotExist=true
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:${REDIS_PORT}
    volumes:
      - .:/usr/src/app
    command: yarn start:dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis
      - mysql
  redis: # Name of container
    image: arm64v8/redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD} --port ${REDIS_PORT}
    volumes: 
      - redis:/data
  mysql:
    image: arm64v8/mysql:8.0
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
  redis:
    driver: local