export default () => ({
  env: process.env.NODE_ENV || 'development',
  port: parseInt(process.env.PORT, 10) || 3000,
  jwt_secret_key: process.env.JWT_SECRET_KEY,
  jwt_expires_in: process.env.JWT_EXPIRATION_TIME,
  database: {
    mysql: {
      host: process.env.MYSQL_HOST,
      port: parseInt(process.env.MYSQL_PORT, 10) || 3306,
      username: process.env.MYSQL_USERNAME,
      password: process.env.MYSQL_PASSWORD,
      database: process.env.MYSQL_DATABASE,
    },
    redis: {
      host: process.env.REDIS_HOST,
      port: parseInt(process.env.REDIS_PORT, 10) || 6379,
      password: process.env.REDIS_PASSWORD,
      url: process.env.REDIS_URL,
    },
  },
  mail: {
    enabled: process.env.MAIL_ENABLED === 'true',
    host: process.env.MAIL_HOST,
    port: parseInt(process.env.MAIL_PORT, 10) || 587,
    username: process.env.MAIL_USERNAME,
    password: process.env.MAIL_PASSWORD,
  },
  store: {
    prices: {
      BR1: {
        IP: 0.0006,
        RP: 0.01481481,
      },
      EUW1: {
        IP: 0.0006,
        RP: 0.0005,
      },
    },
  },
  riot: {
    auth: {
      riot_url: 'https://auth.riotgames.com',
      hydra_url: 'https://api.hydranetwork.org',
      hydra_key: process.env.HYDRA_AUTH_KEY,
    },
    login_queue_url: {
      BR1: 'https://usw2-green.pp.sgp.pvp.net',
      EUN1: 'https://euc1-green.pp.sgp.pvp.net',
      EUW1: 'https://euc1-green.pp.sgp.pvp.net',
      LA1: 'https://usw2-green.pp.sgp.pvp.net',
      LA2: 'https://usw2-green.pp.sgp.pvp.net',
      NA1: 'https://usw2-green.pp.sgp.pvp.net',
      OC1: 'https://apse1-green.pp.sgp.pvp.net',
      RU: 'https://euc1-green.pp.sgp.pvp.net',
      TR1: 'https://euc1-green.pp.sgp.pvp.net',
      JP1: 'https://apne1-green.pp.sgp.pvp.net',
      SG2: 'https://apse1-green.pp.sgp.pvp.net',
      PH2: 'https://ph2-red.lol.sgp.pvp.net',
      VN2: 'https://apse1-green.pp.sgp.pvp.net',
    },
    ledge_url: {
      BR1: 'https://br-red.lol.sgp.pvp.net',
      EUN1: 'https://eune-red.lol.sgp.pvp.net',
      EUW1: 'https://euw-red.lol.sgp.pvp.net',
      LA1: 'https://lan-red.lol.sgp.pvp.net',
      LA2: 'https://las-red.lol.sgp.pvp.net',
      NA1: 'https://na-red.lol.sgp.pvp.net',
      OC1: 'https://oce-red.lol.sgp.pvp.net',
      RU: 'https://ru-red.lol.sgp.pvp.net',
      TR1: 'https://tr-red.lol.sgp.pvp.net',
      JP1: 'https://jp-red.lol.sgp.pvp.net',
      KR: 'https://kr-red.lol.sgp.pvp.net',
      SG2: 'https://sg2-red.lol.sgp.pvp.net',
      PH2: 'https://ph2-red.lol.sgp.pvp.net',
      VN2: 'https://vn2-red.lol.sgp.pvp.net',
    },
    riot_games_account_api_url: 'https://api.account.riotgames.com',
  },
});
